### ISSUE TITLE
Unable to run benchmark scripts

### ISSUE THREAD

**Issue by minkimcello** [checkly/headless-benchmarks#1]
I read the [Cypress vs Selenium vs Playwright vs Puppeteer speed comparison](https://blog.checklyhq.com/cypress-vs-selenium-vs-playwright-vs-puppeteer-speed-comparison/) post. I wanted to run the benchmark locally and add [BigTest](https://frontside.com/bigtest/platform) to the comparison to see how it fares but came across some issues such as:

- `wdio selenium & devtools` are missing spec files
- `playwrite` and `puppeteer` have promise/compiling errors
- `cypress` is missing for the `checkly-suite` test and the tests for `checkly` and `danube` are all failing. Also it seems both scripts are running the test suites for all three scenarios.

Before I ran the shell scripts at the root of the repo, I `npm install`'d in each of the directory that has a `package.json`. Could it perhaps be you forgot to push your latest commits? @ragog

**Comment by ragog** [comment]
Hi @minkimcello - you guessed right and quite some changes had not been pushed yet. Not only that, but in general my local setup was messy after the latest round of changes and needed some refactoring until others would be able to use it. I put some time into it today and it should be way more approachable.

Right now you should be able to follow along the README and get everything set up. If you stumble into additional issues, could you please post the logs for each error you are getting?

**Comment by minkimcello** [comment]
@ragog Thank you for your quick response. I was able to get all of the `danube` tests to run successfully. However, I had less luck with the `checkly` tests:

- `checkly`
  - `cypress`: unable to find `#create-check-button__BV_button_`; perhaps it was a permissions-related UI? Because I manually went into the website and looked for it in the inspector but couldn't find it either
    - removing this click allowed me to run the test successfully
  - `puppeteer`: the tests would complete in one tenth of a second every time so I suspect it's a false positive. the exit code shows as 0 and no error logs are given in `logs/`, `performance/`, nor in the terminal.
  - `webdrivers:devtools`: each run takes 30 seconds to run with no error logs and also with a normal exit code 0
  - `webdriver:selenium` and `playwright`: these seem to be okay but given the issues in `puppeteer` and `devtools` i can't be entirely sure that these weren't false positives
  
- `checkly suite`: i was able to get better error logs from these test suites
  - `cypress`:
    - alert test error:
      ```
      1) Actions
        checkly snippet test:
        AssertionError: Timed out retrying after 35000ms: Expected to find element: `.mb-3:nth-child(4) > .d-flex > .btn`, but never found it.
          at Context.eval (https://app-test.checklyhq.com/__cypress/tests?p=scripts/cypress/checkly-alerts.js:108:8)
      ```
    - snippet test error:
      ```
      1) Actions
         checkly snippet test:
         AssertionError: Timed out retrying after 35000ms: Expected to find element: `#add-snippet`, but never found it.
           at Context.eval (https://app-test.checklyhq.com/__cypress/tests?p=scripts/cypress/checkly-snippet.js:108:8)
       ```
  - `playwright`:
    ```
    Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Error:
      page.click: Protocol error (Runtime.callFunctionOn): Target closed.
        =========================== logs ===========================
          waiting for selector ".octicon-trash"
            selector resolved to visible <svg width="16" height="16" version="1.1" aria-hidden…>…</svg>
          attempting click action
            waiting for element to be visible, enabled and not moving
            element is visible, enabled and does not move
            scrolling into view if needed
            done scrolling
            checking that element receives pointer events at (1235,562)
            <iframe allowfullscreen="" data-intercom-frame="true" cl…></iframe> from <div id="intercom-container" class="intercom-namespac…>…</div> subtree intercepts pointer events
    ```
  - `puppeteer`:
    ```
    Node is either not visible or not an HTMLElement
      waitForSelector(
         #delete-alert-channel-modal__BV_body_ .btn-danger'
         ElementHandle._clickablePoint (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js
    ```
  - `webdriver:devtools`: takes over a minute to run each time with exit code 1 but no errors
  - `webdriver:selenium`:
    ```
    [0-0] [90m2021-02-03T03:28:52.074Z[39m [31mERROR[39m [97mwebdriver[39m: Request failed with status 400 due to element click intercepted: element click intercepted: Element <button class="btn btn-success ml-auto">...</button> is not clickable at point (660, 414). Other element would receive the click: <iframe allowfullscreen="" class="intercom-k70bnj e1gfsz3r0" name="intercom-notifications-frame" title="Intercom live chat message" data-intercom-frame="true"></iframe>
    (Session info: headless chrome=88.0.4324.96)
    [0-1] [90m2021-02-03T03:29:01.989Z[39m [31mERROR[39m [97mwebdriver[39m: Request failed with status 400 due to element click intercepted: element click intercepted: Element <button id="run-request-button" class="btn btn-primary run">...</button> is not clickable at point (728, 473). Other element would receive the click: <iframe allowfullscreen="" class="intercom-k70bnj e1gfsz3r0" name="intercom-notifications-frame" title="Intercom live chat message" data-intercom-frame="true"></iframe>
    (Session info: headless chrome=88.0.4324.96)
    ```
    
Also, I'm not sure why Selenium's start-up time was not included in the benchmark times whereas Cypress' was.

**Comment by ragog** [comment]
@minkimcello thank you for the detailed feedback, this helped me zero in on some issues I had missed. I have now re-tested all the scripts from scratch and rewritten the README to include some important prerequisites. These additional steps should solve most of the remaining issues.

One exception was:
  - `puppeteer`: somehow the script was missing several lines and was completing "successfully" without actually executing the test at all; resolved

Also
> I'm not sure why Selenium's start-up time was not included in the benchmark times whereas Cypress' was.

We did not explicitly measure the startup time, but it was hard to ignore the fact that, contrary to the other tools, Cypress seemed to need quite some seconds before the first test action was performed.
